apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mywebb-rs
spec:
  replicas: 3
  selector:
    matchLabels:
       env: production
  template:
    metadata:
     name: myweb-pod
     labels:
       env: production
    spec:
      containers:
      - name: myweb-con   
        image: vimal13/apache-webserver-php
        